# General control section
Source:
Section: "python"
Priority:
Maintainer: "MOS Horizon Team <mos-horizon@mirantis.com>"
XSBC-Original-Maintainer:
Uploaders:
Build-Depends:
  OnlyIf: {"pbr": [{">=": "0.10"}], "python-all": [{">=": "2.7.1"}], "debhelper": [{">=": "9"}]}
Build-Depends-Indep:
  OnlyIf: {"pbr": [{">=": "0.10"}], "python-all": [{">=": "2.7.1"}], "debhelper": [{">=": "9"}]}
Build-Conflicts:
X-Python-Version:
Standards-Version:
Homepage:
Vcs-Svn:
Vcs-Browser:
XS-Testsuite: 

# Packages section
# "Package" is necessary field
Package:
  "python-gabbi":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
      OnlyIf: {"pbr": [{">=": "0.10"}]}
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: "/usr/lib"
    Main: True
  "python-gabbi-doc":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
      OnlyIf: {"pbr": [{">=": "0.10"}]}
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: ""
    Main: 

# If "True" then nothing will be update
# according global requirements
Update: True

# If "True" then only packages with
# bounds already set will be updated
UpdateIfBounds: 

# Listed bound will be deleted in all packages
# ["<<", ">>", "<=", ">=", "==", "!="]
DelBounds: ["<<", "<=", "!="]

# If "True" then packages that didn't match
# any package in main base will be checked
# in "control-internal" base
ControlInternal: True

# Credentials section
Login: ""
Password: ""
Branch: kilo

# Rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3, sphinxdoc
BuildWith: python2

# Changelog section
PakageName: 
Version: 
# Example of revision: "-1~u14.04+mos1"
Revision: 
  Main: 
  # Just appends some to the end of revision
  Append: 
Tag: 
Urgency: 