Source:
Section: "python"
Priority:
Maintainer:
Build-Depends:
"a":
  - ">=": "0.8"
  - "<": "0.9"
"b":
  - ">=": "0.1.1"
  - "<=": "0.2.9"
Build-Depends-Indep:
Standards-Version:
Homepage:
Package:
Architecture:
Depends:
Description:

Login: dtrishkin@mirantis.com
Password: 3393YEShq27
Branch: juno