# general control section
Source:
Section: "python"
Priority:
Maintainer:
Build-Depends: {"python-django-common": []}
# {"pbr": [{">=", "0.5"}]}
Build-Depends-Indep:
Standards-Version:
Homepage:

# packages section
# "Package" is necessary field
Package:
  "python-django":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
  "python-django-common":
    Architecture: any
    Section:
    Pre-Depends:
    Depends:
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
# {"python-pbr-doc": {Architecture: "any", Section: "doc"}}

# Credentials section
Login: dtrishkin@mirantis.com
Password: "3393YEShq27ops"
Branch: master

# rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3
BuildWith: python2