# general control section
Source:
Section: "python"
Priority:
Maintainer:
Build-Depends:
Build-Depends-Indep:
Standards-Version:
Homepage:

# packages section
# "Package" is necessary field
Package:
  "a":
    - Architecture:
    - Section:
    - Depends:
    - Conflicts:
    - Provides:
    - Breaks:
    - Replaces:
    - Recommends:
    - Suggests:
    - Description:
  "b":
    - Architecture:
    - Section:
    - Depends:
    - Conflicts:
    - Provides:
    - Breaks:
    - Replaces:
    - Recommends:
    - Suggests:
    - Description:

# Credentials section
Login: dtrishkin@mirantis.com
Password: ""
Branch: master

# rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3
BuildWith: python2