Source:
Section: "python"
Priority:
Maintainer:
Build-Depends:
Build-Depends-Indep:
Standards-Version:
Homepage:
Package:
Architecture:
Depends:
  "pbr": [{">" : 0.5}]
Description:

Login: dtrishkin@mirantis.com
Password:
Branch: master
