# general control section
Source:
Section: "python"
Priority:
Maintainer:
XSBC-Original-Maintainer:
Uploaders:
Build-Depends:
  OnlyIf: {"pbr": [{">=": "0.10"}]}
Build-Depends-Indep:
Build-Conflicts:
X-Python-Version:
Standards-Version:
Homepage:
Vcs-Svn:
Vcs-Browser:

# packages section
# "Package" is necessary field
Package:
  "python-oslotest":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
      OnlyIf: {"pbr": [{">=": "0.10"}]}
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: ""
  "python-oslotest-doc":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: ""

# If "True" then nothing will be update
# according global requirements
Update: False

# Credentials section
Login: ""
Password: ""
Branch: master

# rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3, sphinxdoc
BuildWith: python2