# general control section
Source:
Section: "python"
Priority:
Maintainer:
XSBC-Original-Maintainer:
Uploaders:
Build-Depends: # {"pbr": [{">=", "0.5"}]}
Build-Depends-Indep:
Build-Conflicts:
X-Python-Version:
Standards-Version:
Homepage:
Vcs-Svn:
Vcs-Browser:

# packages section
# "Package" is necessary field
Package:
  "python-eventlet":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files:

# Credentials section
Login: ""
Password: ""
Branch: master

# rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3, sphinxdoc
BuildWith: python2