# general control section
Source:
Section: "python"
Priority:
Maintainer:
Build-Depends: # {"pbr": [{">=", "0.5"}]}
Build-Depends-Indep:
Standards-Version:
Homepage:

# packages section
# "Package" is necessary field
Package:
  "python-gabbi":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: "usr/bin;usr/lib"
  "python-gabbi-common":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: "usr/share/doc"

# Credentials section
Login: ""
Password: ""
Branch: master

# rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3
BuildWith: python2