# general control section
Source:
Section: "python"
Priority:
Maintainer: "MOS Oslo Team <mos-oslo@mirantis.com>"
XSBC-Original-Maintainer:
Uploaders:
Build-Depends:
  OnlyIf: {"pbr": [{">=": "0.10"}], "python-all": [{">=": "2.7.1"}], "debhelper": [{">=": "9"}]}
Build-Depends-Indep:
  OnlyIf: {"pbr": [{">=": "0.10"}], "python-all": [{">=": "2.7.1"}], "debhelper": [{">=": "9"}]}
Build-Conflicts:
X-Python-Version:
Standards-Version:
Homepage: "http://launchpad.net/oslo"
Vcs-Svn:
Vcs-Git:
Vcs-Arch:
Vcs-Bzr:
Vcs-Cvs:
Vcs-Darcs:
Vcs-Hg:
Vcs-Mtn:
Vcs-Browser:
XS-Testsuite: 

# packages section
# "Package" is necessary field
Package:
  "python-oslo-versionedobjects":
    Architecture:
    Section:
    Pre-Depends:
    Depends:
      OnlyIf: {"pbr": [{">=": "0.10"}]}
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: "usr/lib"
    Main: True
  "python-oslo-versionedobjects-doc":
    Architecture:
    Section:
    Pre-Depends:
    Depends: {"python-oslo-versionedobjects": [{"=": "${binary:Version}"}],
      OnlyIf: {"pbr": [{">=": "0.10"}]}
    }
    Conflicts:
    Provides:
    Breaks:
    Replaces:
    Recommends:
    Suggests:
    Description:
    Files: "doc/source/* /usr/share/doc/"
    Main: 

# If "True" then nothing will be update
# according global requirements
Update: True

# If "True" then epoch will be set to
# all packages which have it
SetEpoch: 

# If "True" then only packages with
# bounds already set will be updated
UpdateIfBounds: 

# Listed bound will be deleted in all packages
# ["<<", ">>", "<=", ">=", "==", "!="]
DelBounds: ["<<", "<=", "!="]

# If "True" then packages that didn't match
# any package in main base will be checked
# in "control-internal" base
ControlInternal: 

# Credentials section
Login: ""
Password: ""
Branch: kilo

# rules section
# pybuild, python_distutils
Buildsystem: python_distutils
# python2, python3, sphinxdoc
BuildWith: python2

# changelog section
PakageName: 
Version: 
# Example of revision: "-1~u14.04+mos1"
Revision: 
  Main: 
  Append: 
Tag: 
Urgency: 

BuildExcepts: {"python-distutils.core" : {}, "python-sys" : {}, "python-setup" : {},
  "python-argparse" : {}, "python-ordereddict" : {},
  "python-multiprocessing": {}, "python-os": {}}