Document: python-aioeventlet
Title: Debian python-aioeventlet Manual
Author: <insert document author here>
Abstract: This manual describes what python-aioeventlet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-aioeventlet/python-aioeventlet.sgml.gz

Format: postscript
Files: /usr/share/doc/python-aioeventlet/python-aioeventlet.ps.gz

Format: text
Files: /usr/share/doc/python-aioeventlet/python-aioeventlet.text.gz

Format: HTML
Index: /usr/share/doc/python-aioeventlet/html/index.html
Files: /usr/share/doc/python-aioeventlet/html/*.html
